[project]
name = "pjmf-covid"
version = "0.1.0"
description = "US COVID-19 Hospitalization Dashboard"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.32",
    "pandas>=2.0",
    "plotly==5.22.0",
    "pydeck",
]

[tool.poetry]
package-mode = false
